domain: '0ad'
username: 'testbot'
pass: '$2b$12$Zip6SphwhrnXdgUYX5cDt.ljSon/VqZ2LsKu5k7zMdnWNfg8BVx2q'
name: 'BK Shrinandhan'
summary: '<p>I am a <strong> 💻💻💻💻💻💻 Enthusiast </strong></p>'
https: True
icon_url: 'https://0bba-2405-201-e026-50c6-75f0-90f0-1952-4589.ngrok.io/static/nopic.png'
